#!/bin/bash

CONF="/etc/gptcmd/gptcmd.conf"
CREDS_FILE="$HOME/.gptcmd/credentials"

if [ -f "$CONF" ]; then
  set -o allexport;
  source "$CONF";
  set +o allexport;
else
  echo "$CONF not found";
  exit 1;
fi;

if [ -z "$GPT_TOKEN" ]; then
  if [ -f "$CREDS_FILE" ]; then
    set -o allexport;
    source "$CREDS_FILE";
    set +o allexport;
  else
    echo "$CREDS_FILE not found";
    exit 1;
  fi;
fi;

TRAIN=$(cat "$HOME/mks/gpt-cmd/train.txt" | sed -z "s/\n/$STOP/g;s/$STOP$/\n/")
QUESTION="$TRAIN$STOP\0Q:$*$STOP"

BD=$(jq -n '{prompt: $prompt, temperature: $temp, max_tokens: $maxt, top_p: $topp, frequency_penalty: $freq, presence_penalty: $pres, stop: $stop}'\
  --arg prompt "$QUESTION" \
  --argjson temp $TEMPERATURE \
  --argjson maxt $MAX_TOKENS \
  --argjson topp $TOP_P \
  --argjson freq $FREQUENCY_PENALTY \
  --argjson pres $PRESENCE_PENALTY \
  --arg stop "$STOP")

RESP=$(curl -s "https://api.openai.com/v1/engines/$ENGINE/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $GPT_TOKEN" \
  -d "$BD")

TEXT=$(echo $RESP | jq -r .choices[0].text | grep -oP '(?<=A:).*' | tail -1)

echo "$TEXT"
